### ISSUE TITLE
Can't connect to socket server deployed on heroku server

### ISSUE THREAD

**Issue by vineetkumar19871503** [davidstoneham/react-native-sockets#2]
My server is deployed on heroku and I am trying to connect to that server using react native application. It requires both ip address and port of server which is not provided by heroku server as they are not static. How to connect to heroku deployed server?

**Comment by davidstoneham** [comment]
You should be able to use the DNS name of your heroku server if you do not have a static ip address

**Comment by Djinne** [comment]
port would be 443 for https
